version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/healthcare-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=banco123

  db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=healthcare-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data